
services:


  mongo:
    image: mongo
    restart: always
    container_name: mongo-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: neox24

    volumes:
      - mongodb-data:/data/db
    networks:
      - neox

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: neox24
      ME_CONFIG_MONGODB_URL: mongodb://root:neox24@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - neox
networks:
  neox:
    external: true

volumes:
  mongodb-data:
    external: false