spring:
  application:
    name: authorization
  data:
    mongodb:
      uri: ${DB_URL:mongodb://root:rslan24@localhost:27017/auth?authSource=admin}
server:
  servlet:
    context-path: /api
  port: 8045
key:
  access: ${ACCESS_SECRET}
  refresh: ${REFRESH_SECRET}

#debug: true

#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE
