spring:
  application:
    name: authorization
  data:
    mongodb:
      uri: ${DB_URL}
server:
  servlet:
    context-path: /api
  port: ${PORT:8045}
key:
  access: ${ACCESS_SECRET}
  refresh: ${REFRESH_SECRET}

#debug: true

#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE
